name: iaqapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_form_kit: ^5.0.0+1
  flutter_secure_storage_x: ^11.0.0
  google_places_flutter: ^2.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.2
  flutter_dotenv: ^5.2.0

  csv: ^6.0.0
  path_provider: ^2.1.1
  path_provider_android: ^2.2.1

  open_file: ^3.3.2
  image_picker: ^1.1.2
  path: ^1.8.3
  provider: ^6.1.2
  excel: ^4.0.6
  flutter_email_sender: ^7.0.0
  permission_handler: ^12.0.0+1

  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_auth: ^5.5.4
  firebase_app_check: ^0.3.2+7
  cloud_functions: ^5.5.2

  google_sign_in: ^6.2.1
  connectivity_plus: ^6.1.4
  sqflite: ^2.3.2
  uuid: ^4.2.2
  share_plus: ^11.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_api_headers: ^4.5.1
  http: ^1.4.0
  image: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/Roboto-Regular.ttf

