// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_KEY']!,
    appId: '1:1069851910435:web:07576f23e7c3a611322c96',
    messagingSenderId: '1069851910435',
    projectId: 'windows-9e44e',
    authDomain: 'windows-9e44e.firebaseapp.com',
    storageBucket: 'windows-9e44e.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_KEY']!,
    appId: '1:1069851910435:android:603e4983c6aad658322c96',
    messagingSenderId: '1069851910435',
    projectId: 'windows-9e44e',
    storageBucket: 'windows-9e44e.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_KEY']!,
    appId: '1:1069851910435:ios:65850f2948e4ee71322c96',
    messagingSenderId: '1069851910435',
    projectId: 'windows-9e44e',
    storageBucket: 'windows-9e44e.firebasestorage.app',
    iosBundleId: 'com.iaquick.app',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_KEY']!,
    appId: '1:1069851910435:ios:2df55a0128486953322c96',
    messagingSenderId: '1069851910435',
    projectId: 'windows-9e44e',
    storageBucket: 'windows-9e44e.appspot.com',
    iosBundleId: 'com.example.iaqapp.RunnerTests',
  );
}