ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path('../Flutter/Generated.xcconfig', __FILE__)
  File.readlines(generated_xcode_build_settings_path).grep(/FLUTTER_ROOT\=(.*)/) { return $1.strip }
  raise "FLUTTER_ROOT not found in Generated.xcconfig. Run `flutter pub get` first."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
